const router=require('express').Router();
const multer=require('multer');
const controller=require('./galpao.controller');
const {auth}=require('../../middlewares/auth.middleware');
const {requireModuleAccess}=require('../../middlewares/module-access.middleware');
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:100*1024*1024},fileFilter:(req,file,cb)=>cb(null,/\.db$/i.test(file.originalname))});
router.use(auth,requireModuleAccess('galpao'));
router.get('/dashboard',controller.dashboard);
router.get('/produtos',controller.listProducts);
router.post('/produtos',controller.createProduct);
router.put('/produtos/:id',controller.updateProduct);
router.get('/estoque',controller.listStock);
router.get('/produtos/:id/estoque',controller.stockForProduct);
router.post('/entradas',controller.entry);
router.post('/saidas',controller.exit);
router.get('/historico',controller.history);
router.get('/validades',controller.expiry);
router.post('/importar/preview',upload.single('arquivo'),controller.previewImport);
router.post('/importar',upload.single('arquivo'),controller.executeImport);
module.exports=router;
